# Generated by Django 5.1.4 on 2025-02-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='how_to_use',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='key_benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='manufacturer_address',
            field=models.TextField(default='thrissur round ,kerala', max_length=500),
        ),
        migrations.AddField(
            model_name='medicine',
            name='other_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='safety_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
