# Generated by Django 5.1.4 on 2025-03-24 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
