# Generated by Django 5.1.4 on 2025-03-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
