# Generated by Django 5.1.4 on 2025-03-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_alter_order_address_remove_orderitem_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(default='Default Address'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
