# Generated by Django 5.1.4 on 2025-03-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_remove_order_user_cart_cartitems_orders_orderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='payment_method',
        ),
    ]
