# Generated by Django 5.1.4 on 2025-03-28 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0018_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('category', models.CharField(max_length=100)),
                ('is_trending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicine'),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.products'),
        ),
        migrations.AddConstraint(
            model_name='cartitems',
            constraint=models.CheckConstraint(condition=models.Q(('medicine__isnull', False), ('product__isnull', False), _connector='OR'), name='cart_item_has_medicine_or_product'),
        ),
        migrations.AddConstraint(
            model_name='cartitems',
            constraint=models.CheckConstraint(condition=models.Q(('medicine__isnull', False), ('product__isnull', False), _negated=True), name='cart_item_not_both_medicine_and_product'),
        ),
    ]
