# Generated by Django 5.1.4 on 2025-03-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0020_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='prescription',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
