# Generated by Django 5.1.4 on 2025-03-30 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0021_cartitems_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.products'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('medicine__isnull', False), ('product__isnull', False), _connector='OR'), name='order_item_has_medicine_or_product'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('medicine__isnull', False), ('product__isnull', False), _negated=True), name='order_item_not_both_medicine_and_product'),
        ),
    ]
