# Generated by Django 5.1.4 on 2025-04-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0022_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
