# Generated by Django 5.1.4 on 2025-05-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0024_alter_orders_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='prescription',
            field=models.FileField(blank=True, null=True, upload_to='order_prescriptions/'),
        ),
    ]
