# Generated by Django 5.1.4 on 2025-03-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctoradditionalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='is_video_link_sent',
            field=models.BooleanField(default=False),
        ),
    ]
