# Generated by Django 5.1.4 on 2025-03-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_appointments_is_video_link_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointments',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
